USE shopify_db;

LOAD DATA INFILE '/var/lib/mysql-files/PRODUCT.csv' INTO TABLE PRODUCTS
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ID, TITLE, PRICE, INVENTORY_COUNT);